cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer install
    - pecl install libsodium
    - if [ '' != "$SYMFONY_VERSION" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
    - if [ '7.0' != "$TRAVIS_PHP_VERSION" ]; then composer require paragonie/random_compat; fi

branches:
    only:
        - master

language: php

matrix:
    include:
        - php: 5.4
          env: SYMFONY_VERSION='2.3.*'
        - php: 5.4
          env: SYMFONY_VERSION='2.7.*'
        - php: 5.4
          env: SYMFONY_VERSION='2.8.*'
        - php: 7.0
          env: SYMFONY_VERSION='2.3.*'
        - php: 7.0
          env: SYMFONY_VERSION='2.7.*'
        - php: 7.0
          env: SYMFONY_VERSION='2.8.*'

php:
    - 5.4
    - 7.0

sudo: false
