cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - bash .travis/install/libsodium.sh
    - bash .travis/install/uuid.sh
    - phpenv config-rm xdebug.ini
    - bash .travis/install/composer.sh
    - phpenv config-add .travis/extensions.ini

branches:
    only:
        - master

language: php

matrix:
    allow_failures:
    include:
        - php: 5.6
          env: SYMFONY_VERSION='^2.8.0'
        - php: 5.6
          env: SYMFONY_VERSION='^3.0'
        - php: 7.0
          env: SYMFONY_VERSION='^2.8.0'
        - php: 7.0
          env: SYMFONY_VERSION='^3.0'
        - php: 7.1
          env: SYMFONY_VERSION='^2.8.0'
        - php: 7.1
          env: SYMFONY_VERSION='^3.0'

php:
    - 5.6
    - 7.0
    - 7.1

sudo: required
