cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - bash .travis/install/libsodium.sh
    - bash .travis/install/uuid.sh
    - bash .travis/install/composer.sh
    - phpenv config-add .travis/extensions.ini

branches:
    only:
        - master

language: php

matrix:
    allow_failures:
        - php: 5.4
          env: SYMFONY_VERSION='3.0.*'
        - php: 7.0
          env: SYMFONY_VERSION='3.0.*'
    include:
        - php: 5.4
          env: SYMFONY_VERSION='2.3.*'
        - php: 5.4
          env: SYMFONY_VERSION='2.7.*'
        - php: 5.4
          env: SYMFONY_VERSION='2.8.*'
        - php: 7.0
          env: SYMFONY_VERSION='2.3.*'
        - php: 7.0
          env: SYMFONY_VERSION='2.7.*'
        - php: 7.0
          env: SYMFONY_VERSION='2.8.*'

php:
    - 5.4
    - 7.0

sudo: required
